config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  get 'pages/about'

  resources :product_backlog_items do
    resources :sprint_tasks do
    	member do
    		patch :complete
    	end
    end
  end

  root "product_backlog_items#index"

end

app/models/product_backlog_item.rb
class ProductBacklogItem < ActiveRecord::Base
  has_many :sprint_tasks
end

app/models/sprint_task.rb
class SprintTask < ActiveRecord::Base
  belongs_to :product_backlog_item

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/product_backlog_items_controller.rb
class ProductBacklogItemsController < ApplicationController
  before_action :set_product_backlog_item, only: [:show, :edit, :update, :destroy]

  # GET /product_backlog_items
  # GET /product_backlog_items.json
  def index
    @product_backlog_items = ProductBacklogItem.all
  end

  # GET /product_backlog_items/1
  # GET /product_backlog_items/1.json
  def show
  end

  # GET /product_backlog_items/new
  def new
    @product_backlog_item = ProductBacklogItem.new
  end

  # GET /product_backlog_items/1/edit
  def edit
  end

  # POST /product_backlog_items
  # POST /product_backlog_items.json
  def create
    @product_backlog_item = ProductBacklogItem.new(product_backlog_item_params)

    respond_to do |format|
      if @product_backlog_item.save
        format.html { redirect_to @product_backlog_item, notice: 'Product backlog item was successfully created.' }
        format.json { render :show, status: :created, location: @product_backlog_item }
      else
        format.html { render :new }
        format.json { render json: @product_backlog_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_backlog_items/1
  # PATCH/PUT /product_backlog_items/1.json
  def update
    respond_to do |format|
      if @product_backlog_item.update(product_backlog_item_params)
        format.html { redirect_to @product_backlog_item, notice: 'Product backlog item was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_backlog_item }
      else
        format.html { render :edit }
        format.json { render json: @product_backlog_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_backlog_items/1
  # DELETE /product_backlog_items/1.json
  def destroy
    @product_backlog_item.destroy
    respond_to do |format|
      format.html { redirect_to product_backlog_items_url, notice: 'Product backlog item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_backlog_item
      @product_backlog_item = ProductBacklogItem.find(params[:id])
    end

    def set_sprint_task
		  @sprint_task = @product_backlog_item.sprint_tasks.find(params[:id])
	  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_backlog_item_params
      params.require(:product_backlog_item).permit(:item, :priority, :initialsizeestimate)
    end
end

app/controllers/sprint_tasks_controller.rb
class SprintTasksController < ApplicationController
  before_action :set_product_backlog_item
	before_action :set_sprint_task, except: [:create]

	def create
    @sprint_task = @product_backlog_item.sprint_tasks.create(sprint_task_params)
    redirect_to @product_backlog_item
	end

	def destroy
		if @sprint_task.destroy
			flash[:success] = "Sprint task was deleted."
		else
			flash[:error] = "Sprint task could not be deleted."
		end
    redirect_to @product_backlog_item
	end

	def complete
		@sprint_task.update_attribute(:completed_at, Time.now)
    redirect_to @product_backlog_item, notice: "Product backlog item completed"
	end

	private

	def set_product_backlog_item
    @product_backlog_item = ProductBacklogItem.find(params[:product_backlog_item_id])
	end

	def set_sprint_task
		@sprint_task = @product_backlog_item.sprint_tasks.find(params[:id])
	end

	def sprint_task_params
    params[:sprint_task].permit(:content)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_backlog_items_helper.rb
module ProductBacklogItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commuteapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/product_backlog_items/_form.html.erb
<%= form_for(@product_backlog_item) do |f| %>
  <% if @product_backlog_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_backlog_item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @product_backlog_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>

  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :initialsizeestimate %><br>
    <%= f.text_field :initialsizeestimate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_backlog_items/edit.html.erb
<h1 class="todo_list_title">Edit Product Backlog Item</h1>
<br/>
<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', product_backlog_items_path %>
</div>

app/views/product_backlog_items/index.html.erb
<% @product_backlog_items.each do |product_backlog_item| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to product_backlog_item.item, product_backlog_item %></h2>
  </div>
<% end %>

<div class="links">
  <%= link_to 'New Product backlog item', new_product_backlog_item_path %>
</div>

app/views/product_backlog_items/new.html.erb
<h1 class="todo_list_title">New Product Backlog Item</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', product_backlog_items_path %>
</div>

app/views/product_backlog_items/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @product_backlog_item.item %></h2>

<div id="todo_items_wrapper">
	<%= render @product_backlog_item.sprint_tasks %>
	<div id="form">
		<%= render "sprint_tasks/form" %>
	</div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_product_backlog_item_path(@product_backlog_item) %> |
  <%= link_to 'Delete', product_backlog_item_path(@product_backlog_item), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', product_backlog_items_path %>
</div>

app/views/sprint_tasks/_form.html.erb
<%= form_for([@product_backlog_item, @product_backlog_item.sprint_tasks.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Task" %>
	<%= f.submit %>
<% end %>

app/views/sprint_tasks/_sprint_task.html.erb
<div class="row clearfix">
	<% if sprint_task.completed? %>
		<div class="complete">
      <%= link_to complete_product_backlog_item_sprint_task_path(@product_backlog_item, sprint_task.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= sprint_task.content %></strike></p>
		</div>
		<div class="trash">
      <%= link_to product_backlog_item_sprint_task_path(@product_backlog_item, sprint_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		<div class="complete">
      <%= link_to complete_product_backlog_item_sprint_task_path(@product_backlog_item, sprint_task.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= sprint_task.content %></p>
		</div>
		<div class="trash">
      <%= link_to product_backlog_item_sprint_task_path(@product_backlog_item, sprint_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>